### ISSUE TITLE
Add instruction to install remotes

### ISSUE THREAD

**Issue by J535D165** [sodascience/osmenrich#2]
Might be good to add instructions to install `remotes` in the installation section of the README.

**Comment by bagheria** [comment]
remotes::install_github("sodascience/osmenrich") works with remotes version 2.2.0 (current version). **One needs to update their installation of remotes.** Otherwise they get the following error:

remotes::install_github("sodascience/osmenrich")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`sodascience`) and repo name (`osmenrich`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by leonardovida** [comment]
@J535D165 I will add instructions for `remotes` installation in the README. 

@bagheria: thank you for the heads up! I have looked up this and it seems related to the recent change from `master` to `main` and the subsequent switch to `HEAD` (see this issue https://github.com/r-lib/remotes/issues/508).

As a matter of fact, `remotes` version `2.1` returns with an even "clearer" error indicating it's due to the "master" naming:
```r
> remotes::install_github("sodascience/osmenrich")
Downloading GitHub repo sodascience/osmenrich@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/sodascience/osmenrich/tarball/master'
```

@J535D165 Re this: I will add a note about using the latest version of `remotes`. But we could also think about users and switch the naming of the branch back to `master`?
