### ISSUE TITLE
Use different reduce function

### ISSUE THREAD

**Issue by J535D165** [sodascience/osmenrich#9]
It seems to be possible to use a different reduce function for the kernel. However, I can't figure out how. 

I thought the syntax would be like the syntax below, but this returns an error. 
``` r
tribble(
  ~person,  ~lat,   ~lon,
  "Alice",  52.12,  5.09,
  "Bob",    52.13,  5.08,
) %>%
sf::st_as_sf(
  coords = c("lon", "lat"), 
  crs = 4326
) %>%
enrich_osm(
  name = "n_waste_baskets",
  key = "amenity",
  value = "waste_basket",
  r = 100,
  FUN=sum,
)
```

**Comment by leonardovida** [comment]
@J535D165 There is an error that explains that, doesn't that get printed? Because of the way we implement `kernels`, users need to add them with the following syntax `function(d, r, fun) fun(d,r)`. Already in #15 I agreed this is less than ideal and we need to rethink the way the package implements kernels to make it much more simple for users to do so. 
I'd like to use this next Thursday (25th Feb) meeting to discuss this.
